name: NPM Publish Package

on:
  push:
    branches: [ master, beta, alpha ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  quality:
    name: Quality Control
    uses: cnpja/workflows/.github/workflows/nodejs_quality_control.yaml@master
    secrets: inherit

  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: |
          npm i -g pnpm
          pnpm i --frozen-lockfile

      - name: Build Distributable
        run: pnpm build

      - name: Publish Package
        env:
          HUSKY: 0
        run: semantic-release
